#!/bin/bash
# Запуск командой ./help_file

# Остановка и удаление всех контейнеров и томов
docker-compose down -v

# Пересборка и запуск контейнеров
docker-compose up -d --build

# Создание и применение миграций
docker-compose exec backend python manage.py makemigrations
docker-compose exec backend python manage.py migrate

# Сборка статических файлов
docker-compose exec backend python manage.py collectstatic --noinput --clear

# Загрузка данных
docker-compose exec backend python manage.py load_ingredients
docker-compose exec backend python manage.py load_users
docker-compose exec backend python manage.py set_default_avatars
docker-compose exec backend python manage.py load_recipes

# Создание суперпользователя с заданными данными
echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('Администратор', 'admin@gmail.com', 'admin', first_name='Юлия', last_name='Петрачкова')" | docker-compose exec -T backend python manage.py shell
